### ISSUE TITLE
Issues  with  building  Vxnaid  code

### ISSUE THREAD

**Issue by ananungiidi** [johnsonandjohnson/vxnaid#1]
Dear Team,
I  have  been  having  issues  with  buidling the  vxnaid  code  in  my  Android  studio.  It  looks  like  their  incompatibilities  with gradle  version as  per  attached  error  message. Please  advise  on  how  I  can resolve  this  issue. I am have  Android  studio giraffe  installed  on my  Windows  computer. 
[error  message.txt](https://github.com/johnsonandjohnson/vxnaid/files/13068133/error.message.txt)

**Comment by ananungiidi** [comment]
Dear  Team, I am inquiring about the  progress of  this  issue.

**Comment by ananungiidi** [comment]
Dear  Team, I  upgraded  the  gradle  version to 7.2 and  that  issue  was  resolved. But  now  I  have  another error arising  from unknown property 'SOLIDARIT
[error  message.txt](https://github.com/johnsonandjohnson/vxnaid/files/13167057/error.message.txt)
Y_STORE_PASSWORD. Please  see  atatched  file  for  error details.

**Comment by sherrif10** [comment]
i was able to run it locally, the issue could be from android sdk dependencies. Lets sit if we get time together and look into it.
