### ISSUE TITLE
Make Iris Scanner configurable from openmrs

### ISSUE THREAD

**Issue by sherrif10** [johnsonandjohnson/vxnaid#2]
Hello @druchniewicz @aagrawa4 . Its kinda hectic if a user wants to go away with iris scanner. suppose i dont want iris scanner into the instance, what do i neeed to do ?

**Comment by druchniewicz** [comment]
Hi @sherrif10 
Please take a look here - https://github.com/johnsonandjohnson/vxnaid/wiki/Configuration-Page#identification-steps
The identification steps are described there.
P.S. For future please do not mention aagrawa4. He's no longer available for CfL project.

**Comment by sherrif10** [comment]
Thanks for quick response @druchniewicz . Its kinda stressing while setting up docker container of vxnaid. Do you have a docker container file that i can setup local vxnaid please. this one is giving me headache.

**Comment by druchniewicz** [comment]
Example of docker compose file can be found here - https://github.com/johnsonandjohnson/openmrs-distro-vxnaid/blob/main/cfl/docker-compose.run.yml

In .env file you define all variables mentioned in docker-compose.run.yml file

**Comment by sherrif10** [comment]
For my case, i want to first do without iris scanner, do you have an example which i can bench mark on, Like already running docker configs that i can use locally. That will be much appreciated.
